require 'px'
PX.dtbgcjbgcbakdubgcjbgbxbwakeienemelbgbidtbgcjbgbibgbrbgdtbuemehdrelakeienemel
PX.bgbidubgcjbgbibgbrbgdubuemehdrelakebdybgdtbgckbgduakeienemelbgbidtbgdzekdxdt
PX.emdxekbgemeadtegbgdubiakdxeeeldxakeienemelbgbidubgdzekdxdtemdxekbgemeadtegbg
PX.dtbiakdxegdwakeienemelbgdtbgbqbgdubgbqbgby
-PX
